### ISSUE TITLE
Question: handling browser vendor prefixed *values*

### ISSUE THREAD

**Issue by basarat** [FormidableLabs/radium#204]
Is there a solution offered for this by radium or any other CSS in JS framework? e.g. the following css: 

```css
  .layout {
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
  }
```
How to represent this in JS?
