### ISSUE TITLE
Many properties get prefixed with "undefined-webkit-" on WebKit-based browsers

### ISSUE THREAD

**Issue by tbassetto** [FormidableLabs/radium#387]
Hi,

I am running io.js 2.5.0 with Radium 0.14.2. If I use this code in a component:

```html
<Style
  rules={{
    div: {
      boxSizing: 'border-box',
      position: 'relative',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      flexShrink: 0,
      alignContent: 'flex-start',
      border: '0 solid black',
      margin: 0,
      padding: 0
    }
  }}
/>
```

The end result in Chrome 46.0.2490.71 and Safari 9.0 is:

```css
div {
    undefined-webkit-box-sizing: border-box;
    position: relative;
    display: flex;
    undefined-webkit-flex-direction: column;
    undefined-webkit-align-items: stretch;
    undefined-webkit-flex-shrink: 0;
    undefined-webkit-align-content: flex-start;
    border: 0 solid black;
    margin: 0;
    padding: 0;
}
```

As you can see all `-webkit-` prefixes became  `undefined-webkit-`. I can reproduce this bug with the latest Radium (git checkout from master) and adding the `<Style />` code to `examples/app.jsx`. The generated code on Firefox 41 looks fine.
