### ISSUE TITLE
Style component hover issue

### ISSUE THREAD

**Issue by alexmarchant** [FormidableLabs/radium#712]
I would expect the following:
```jsx
<Style 
  scopeSelector=".my-class" 
  rules={
    {':hover': {backgroundColor: 'black'}
  }
}/>
```

to create the following output

```css
.my-class:hover {
  background-color: 'black';
}
```

Though in the output there is a space:

```css
.my-class :hover {
  background-color: 'black';
}
```

Maybe the style component can detect :hover, :focus, and :active and remove the space for those?
