### ISSUE TITLE
Implementing Element Queries

### ISSUE THREAD

**Issue by hawsome** [FormidableLabs/radium#770]
Hi!

I was wondering how would I go about using this: http://marcj.github.io/css-element-queries/?

```css
.widget-name h2 {
    font-size: 12px;
}

.widget-name[min-width~="400px"] h2 {
    font-size: 18px;
}

.widget-name[min-width~="600px"] h2 {
    padding: 55px;
    text-align: center;
    font-size: 24px;
}

.widget-name[min-width~="700px"] h2 {
    font-size: 34px;
    color: red;
}
```

Thanks!
