### ISSUE TITLE
table-cell not supported?

### ISSUE THREAD

**Issue by EdmundLeex** [FormidableLabs/radium#870]
I have this. It doesn't throw error in the rendering process. But it breaks my event listener binding. Removing it or changing it to `display: block` can magically fix it.
```css
div: {
  display: 'table'
}
span {
  display: 'table-cell' /* this is breaking */
}
```
